/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AboutMe = IDL.Record({
  'name' : IDL.Text,
  'year' : IDL.Text,
  'course' : IDL.Text,
});
export const NoteId = IDL.Nat;
export const Subject = IDL.Variant({
  'Maths' : IDL.Null,
  'Hindi' : IDL.Null,
  'English' : IDL.Null,
  'Science' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Note = IDL.Record({
  'id' : NoteId,
  'subject' : Subject,
  'author' : IDL.Principal,
  'photo' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAboutMe' : IDL.Func([IDL.Principal], [AboutMe], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNotesBySubject' : IDL.Func([Subject], [IDL.Vec(Note)], ['query']),
  'updateAboutMe' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'uploadNote' : IDL.Func([Subject, ExternalBlob], [NoteId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AboutMe = IDL.Record({
    'name' : IDL.Text,
    'year' : IDL.Text,
    'course' : IDL.Text,
  });
  const NoteId = IDL.Nat;
  const Subject = IDL.Variant({
    'Maths' : IDL.Null,
    'Hindi' : IDL.Null,
    'English' : IDL.Null,
    'Science' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Note = IDL.Record({
    'id' : NoteId,
    'subject' : Subject,
    'author' : IDL.Principal,
    'photo' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAboutMe' : IDL.Func([IDL.Principal], [AboutMe], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNotesBySubject' : IDL.Func([Subject], [IDL.Vec(Note)], ['query']),
    'updateAboutMe' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'uploadNote' : IDL.Func([Subject, ExternalBlob], [NoteId], []),
  });
};

export const init = ({ IDL }) => { return []; };